# Generated by Django 4.1.3 on 2022-11-21 14:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodoviInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_bodovi', models.IntegerField(default=0)),
                ('max_bodovi', models.IntegerField(default=100)),
            ],
            options={
                'unique_together': {('min_bodovi', 'max_bodovi')},
            },
        ),
        migrations.CreateModel(
            name='Ispit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_ispita', models.CharField(max_length=40)),
                ('ispitni_kod', models.CharField(max_length=10)),
                ('ukupan_broj_polagaca', models.IntegerField(default=0)),
                ('vrijeme_trajanja', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('broj_inicijalizacija', models.IntegerField(default=0)),
                ('oblast_ispita', models.CharField(blank=True, max_length=40)),
                ('bodovi_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.bodoviinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Pitanja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tekst', models.CharField(max_length=500)),
                ('max_bodovi', models.IntegerField(default=10)),
                ('vrijeme_trajanja', models.DurationField(default=datetime.timedelta(seconds=30))),
                ('oblast_Pitanja', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RbPitanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rb_pitanja_u_ispitu', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('ime', models.CharField(max_length=25)),
                ('prezime', models.CharField(max_length=25)),
                ('broj_telefona', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Z', 'Zadavac'), ('P', 'Polagac')], default='P', max_length=1)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Polagac',
            fields=[
                ('broj_polaganih_ispita', models.IntegerField(default=0)),
                ('prosjecna_ocjena', models.IntegerField(default=0)),
                ('broj_polozenih_ispita', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zadatak',
            fields=[
                ('odgovor', models.CharField(blank=True, max_length=500)),
                ('default_tacan_odg', models.CharField(blank=True, max_length=500)),
                ('pitanje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ExamApp.pitanja')),
            ],
        ),
        migrations.CreateModel(
            name='Zadavac',
            fields=[
                ('broj_ispita', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zaokruzi',
            fields=[
                ('odgovor1', models.CharField(max_length=250)),
                ('odgovor2', models.CharField(blank=True, max_length=250)),
                ('odgovor3', models.CharField(blank=True, max_length=250)),
                ('tacan_odg', models.CharField(max_length=250)),
                ('izgubljeni_bodovi', models.IntegerField(default=0)),
                ('pitanje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ExamApp.pitanja')),
            ],
        ),
        migrations.CreateModel(
            name='Polaganje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_polaganja', models.DateTimeField(auto_now_add=True)),
                ('vrijeme_pocetka', models.TimeField(auto_now_add=True)),
                ('vrijeme_kraja', models.TimeField()),
                ('ispit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.ispit')),
                ('polagac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.polagac')),
            ],
        ),
        migrations.CreateModel(
            name='PitanjaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_zaokruzi_pitanja', models.IntegerField(default=0)),
                ('broj_zadataka', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('broj_zaokruzi_pitanja', 'broj_zadataka')},
            },
        ),
        migrations.AddField(
            model_name='pitanja',
            name='rb_u_ispitu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.rbpitanja'),
        ),
        migrations.CreateModel(
            name='OcjenaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_ocjena', models.IntegerField(default=5)),
                ('min_prolazna_ocjena', models.IntegerField(default=2)),
            ],
            options={
                'unique_together': {('max_ocjena', 'min_prolazna_ocjena')},
            },
        ),
        migrations.AddField(
            model_name='ispit',
            name='ocjena_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.ocjenainfo'),
        ),
        migrations.AddField(
            model_name='ispit',
            name='pitanja',
            field=models.ManyToManyField(to='ExamApp.pitanja'),
        ),
        migrations.AddField(
            model_name='ispit',
            name='pitanja_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.pitanjainfo'),
        ),
        migrations.CreateModel(
            name='Ocjenjivanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocjena', models.IntegerField(default=1)),
                ('osvojeni_bodovi', models.IntegerField(default=0)),
                ('napomene', models.CharField(blank=True, max_length=100)),
                ('datum_rezultata', models.DateTimeField(auto_now_add=True)),
                ('polaganje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.polaganje')),
                ('zadavac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.zadavac')),
            ],
        ),
        migrations.CreateModel(
            name='Formiranje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_formiranja', models.DateTimeField(auto_now_add=True)),
                ('ispit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.ispit')),
                ('zadavac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.zadavac')),
            ],
        ),
    ]
