# Generated by Django 4.1.3 on 2022-11-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0002_remove_ocjenjivanje_polaganje_ispit_datum_formiranja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ispit',
            name='pitanja',
        ),
        migrations.AddField(
            model_name='pitanja',
            name='ispit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExamApp.ispit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ispit',
            name='ocjena_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ExamApp.ocjenainfo'),
        ),
        migrations.AlterField(
            model_name='ispit',
            name='pitanja_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ExamApp.pitanjainfo'),
        ),
    ]
