# Generated by Django 4.1.3 on 2022-12-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0004_zadavac_broj_neocjenjenih_ispita'),
    ]

    operations = [
        migrations.AddField(
            model_name='ispit',
            name='pokrenut',
            field=models.BooleanField(default=False),
        ),
    ]
