# Generated by Django 4.1.3 on 2022-12-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0005_ispit_pokrenut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polaganje',
            name='vrijeme_kraja',
            field=models.TimeField(blank=True),
        ),
    ]
