# Generated by Django 4.1.3 on 2022-12-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0007_alter_polaganje_vrijeme_kraja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zadatak',
            name='odgovor',
        ),
        migrations.CreateModel(
            name='OdgovorZadatka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odgovor', models.CharField(max_length=500)),
                ('polagac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.polagac')),
                ('zadatak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.zadatak')),
            ],
            options={
                'unique_together': {('zadatak', 'polagac')},
            },
        ),
    ]
