# Generated by Django 4.1.3 on 2023-01-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0008_remove_zadatak_odgovor_odgovorzadatka'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ocjenjivanje',
            unique_together={('zadavac', 'polagac', 'ispit')},
        ),
    ]
