# Generated by Django 4.1.3 on 2023-01-01 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0009_alter_ocjenjivanje_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='odgovorzadatka',
            name='ispit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExamApp.ispit'),
            preserve_default=False,
        ),
    ]
