# Generated by Django 4.1.3 on 2023-01-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0011_ispit_ocjenjen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ispit',
            name='ocjenjen',
        ),
    ]
