# Generated by Django 4.1.3 on 2023-01-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0012_remove_ispit_ocjenjen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocjenjivanje',
            name='ocjenjen',
            field=models.BooleanField(default=False),
        ),
    ]
