# Generated by Django 4.1.3 on 2023-01-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0014_rename_min_prolazna_ocjena_ocjenainfo_min_ocjena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocjenainfo',
            name='min_ocjena',
            field=models.IntegerField(default=1),
        ),
    ]
