# Generated by Django 4.1.3 on 2023-01-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0015_alter_ocjenainfo_min_ocjena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ispit',
            name='bodovi_info',
        ),
        migrations.DeleteModel(
            name='BodoviInfo',
        ),
    ]
