# Generated by Django 4.1.3 on 2023-01-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0016_remove_ispit_bodovi_info_delete_bodoviinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitanja',
            name='rb_u_ispitu',
        ),
        migrations.DeleteModel(
            name='RbPitanja',
        ),
    ]
