# Generated by Django 4.1.3 on 2023-01-10 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0017_remove_pitanja_rb_u_ispitu_delete_rbpitanja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odgovorzadatka',
            name='zadatak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApp.pitanja'),
        ),
    ]
