# Generated by Django 4.1.3 on 2023-01-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0018_alter_odgovorzadatka_zadatak'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pitanjainfo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ispit',
            name='ocjena_info',
        ),
        migrations.RemoveField(
            model_name='ispit',
            name='pitanja_info',
        ),
        migrations.AddField(
            model_name='ispit',
            name='broj_zadataka',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ispit',
            name='broj_zaokruzi_pitanja',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ispit',
            name='max_ocjena',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ispit',
            name='min_ocjena',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='OcjenaInfo',
        ),
        migrations.DeleteModel(
            name='PitanjaInfo',
        ),
    ]
